
# Project ID
project_id = "cslfiwjfivxsgopfpeti"

[api]
# Port to use for the API URL
port = 54321
schemes = ["http", "https"]

[db]
# Port to use for the local database URL
port = 54322

[studio]
# Port to use for Supabase Studio
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually delivered to emails,
# rather they are captured by gotrue and sent to the email testing server to be viewed.
[inbucket]
# Port to use for the email testing server web interface
port = 54324

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

# Configure Edge Functions
[functions]
[functions.create-checkout]
verify_jwt = true
