// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cslfiwjfivxsgopfpeti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzbGZpd2pmaXZ4c2dvcGZwZXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODUwNDgsImV4cCI6MjA2MDk2MTA0OH0.hGSDKr5l91IqRNXb5CvwW5k0l1VFrnnz6rcvCb1qlC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);