

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cslfiwjfivxsgopfpeti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzbGZpd2pmaXZ4c2dvcGZwZXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODUwNDgsImV4cCI6MjA2MDk2MTA0OH0.hGSDKr5l91IqRNXb5CvwW5k0l1VFrnnz6rcvCb1qlC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'wisatajelajah-auth'
  }
});

// Add a debugging helper function to test connection
export const testSupabaseConnection = async (): Promise<{ success: boolean; message: string }> => {
  try {
    console.log('Testing Supabase connection...');
    
    // Try to get the current session as a basic connection test
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Supabase connection test error:', error);
      return { 
        success: false, 
        message: `Failed to connect to Supabase: ${error.message}` 
      };
    }
    
    // Try to query a simple table to test database access
    const { error: profilesError } = await supabase
      .from('profiles')
      .select('count')
      .limit(1);
      
    if (profilesError) {
      console.error('Database access test error:', profilesError);
      return { 
        success: false, 
        message: `Connected to Supabase, but database access failed: ${profilesError.message}` 
      };
    }
    
    console.log('Supabase connection successful, session:', data.session ? 'Active' : 'None');
    
    return { 
      success: true, 
      message: 'Successfully connected to Supabase and database' 
    };
  } catch (err) {
    console.error('Unexpected error testing connection:', err);
    return { 
      success: false, 
      message: `Unexpected error connecting to Supabase: ${String(err)}` 
    };
  }
};

